name: ryu-cho

on:
  # Schedule the interval of the checks.
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          # GitHub access token. Required.
          access-token: ${{ secrets.RYU_CHO_SECRET }}

          # Git user name to use when making issues and PRs. Required.
          username: ryo-gk

          # Git email address to use when making issues and PRs. Required.
          email: "ryo.gk55@gmail.com"

          # The url for the upstream repo. This is the repository that you
          # set up Ryu-Cho. Required.
          upstream-repo: https://github.com/ryo-gk/repository_sandbox_upstream.git

          # The branch for the upstream repo. Optional. Defaults to `main`.
          upstream-repo-branch: main

          # The head repo to track. This is the repository you want to
          # take a diff. Required.
          head-repo: https://github.com/ryo-gk/repository_sandbox_head.git

          # The branch for the head repo. Optional. Defaults to `main`.
          head-repo-branch: main

          # The git commit sha of head repo to start tracking. Ryu-Cho will
          # only track commit from this hash. Required.
          track-from: d104603b0ec87ea93506e3a1661154d898bf9572

          # File path to track. In this example, Ryu-Cho will only track
          # commits that modified files under `docs` folder. Optional.
          path-starts-with: docs/

          # GitHub workflow name that runs Ryu-Cho. This is required since
          # Ryu-Cho determines the last run by looking into last workflow
          # run timestamp. Optional. Defaults to `ryu-cho`.
          workflow-name: ryu-cho